var Rice2020 = [['ReporterCountries', 'PartnerCountries', 'Value'],
    ['Saudi Arabia', 'Argentina', 519],
    ['Saudi Arabia', 'Australia', 4316],
    ['Saudi Arabia', 'Bangladesh', 3798],
    ['Saudi Arabia', 'Brazil', 9836],
    ['Saudi Arabia', 'Bulgaria', 1545],
    ['Saudi Arabia', 'Cambodia', 3302],
    ['Saudi Arabia', 'Canada', 2],
    ['Saudi Arabia', 'China, mainland', 2508],
    ['Saudi Arabia', 'China, Taiwan Province of', 7],
    ['Saudi Arabia', 'Egypt', 567],
    ['Saudi Arabia', 'France', 0],
    ['Saudi Arabia', 'Germany', 3],
    ['Saudi Arabia', 'India', 1199521],
    ['Saudi Arabia', 'Indonesia', 14],
    ['Saudi Arabia', 'Iraq', 56],
    ['Saudi Arabia', 'Italy', 2059],
    ['Saudi Arabia', 'Japan', 5],
    ['Saudi Arabia', 'Lebanon', 0],
    ['Saudi Arabia', 'Netherlands', 2],
    ['Saudi Arabia', 'Pakistan', 126799],
    ['Saudi Arabia', 'Philippines', 63],
    ['Saudi Arabia', 'Portugal', 2401],
    ['Saudi Arabia', 'Republic of Korea', 7],
    ['Saudi Arabia', 'Romania', 21],
    ['Saudi Arabia', 'Russian Federation', 25],
    ['Saudi Arabia', 'Serbia', 40],
    ['Saudi Arabia', 'Spain', 906],
    ['Saudi Arabia', 'Sri Lanka', 113],
    ['Saudi Arabia', 'Thailand', 31377],
    ['Saudi Arabia', 'Turkey', 0],
    ['Saudi Arabia', 'United Arab Emirates', 72],
    ['Saudi Arabia', 'United Kingdom of Great Britain and Northern Ireland', 6],
    ['Saudi Arabia', 'United States of America', 112894],
    ['Saudi Arabia', 'Uzbekistan', 83],
    ['Saudi Arabia', 'Viet Nam', 32292],
];

var Rice2019 = [
    ['ReporterCountries', 'PartnerCountries', 'Value'],
    ['Saudi Arabia', 'Afghanistan', 21],
    ['Saudi Arabia', 'Argentina', 100],
    ['Saudi Arabia', 'Australia', 16176],
    ['Saudi Arabia', 'Bangladesh', 2331],
    ['Saudi Arabia', 'Belgium', 21],
    ['Saudi Arabia', 'Brazil', 10918],
    ['Saudi Arabia', 'Bulgaria', 149],
    ['Saudi Arabia', 'Canada', 1],
    ['Saudi Arabia', 'China, mainland', 924],
    ['Saudi Arabia', 'Egypt', 1100],
    ['Saudi Arabia', 'Germany', 1],
    ['Saudi Arabia', 'India', 1045884],
    ['Saudi Arabia', 'Indonesia', 17],
    ['Saudi Arabia', 'Iraq', 50],
    ['Saudi Arabia', 'Italy', 800],
    ['Saudi Arabia', 'Japan', 1],
    ['Saudi Arabia', 'Malaysia', 2],
    ['Saudi Arabia', 'Pakistan', 134885],
    ['Saudi Arabia', 'Philippines', 271],
    ['Saudi Arabia', 'Portugal', 1612],
    ['Saudi Arabia', 'Republic of Korea', 3],
    ['Saudi Arabia', 'Spain', 1453],
    ['Saudi Arabia', 'Sri Lanka', 67],
    ['Saudi Arabia', 'Thailand', 44520],
    ['Saudi Arabia', 'Turkey', 1],
    ['Saudi Arabia', 'Ukraine', 0],
    ['Saudi Arabia', 'United Arab Emirates', 6],
    ['Saudi Arabia', 'United Kingdom of Great Britain and Northern Ireland', 3],
    ['Saudi Arabia', 'United States of America', 103685],
    ['Saudi Arabia', 'Viet Nam', 27803],
];
var Rice2018 = [
    ['ReporterCountries', 'PartnerCountries', 'Value'],
    ['Saudi Arabia', 'Australia', 30358],
    ['Saudi Arabia', 'Bangladesh', 1964],
    ['Saudi Arabia', 'Belgium', 1],
    ['Saudi Arabia', 'Brazil', 6834],
    ['Saudi Arabia', 'Bulgaria', 72],
    ['Saudi Arabia', 'Cambodia', 558],
    ['Saudi Arabia', 'Canada', 1],
    ['Saudi Arabia', 'China, mainland', 1852],
    ['Saudi Arabia', 'Egypt', 801],
    ['Saudi Arabia', 'France', 2],
    ['Saudi Arabia', 'Germany', 1],
    ['Saudi Arabia', 'Greece', 815],
    ['Saudi Arabia', 'India', 968660],
    ['Saudi Arabia', 'Indonesia', 13],
    ['Saudi Arabia', 'Iraq', 47],
    ['Saudi Arabia', 'Italy', 432],
    ['Saudi Arabia', 'Japan', 3],
    ['Saudi Arabia', 'Lebanon', 51],
    ['Saudi Arabia', 'Mongolia', 48],
    ['Saudi Arabia', 'Pakistan', 93272],
    ['Saudi Arabia', 'Peru', 12],
    ['Saudi Arabia', 'Philippines', 23],
    ['Saudi Arabia', 'Portugal', 2554],
    ['Saudi Arabia', 'Republic of Korea', 2],
    ['Saudi Arabia', 'South Africa', 87],
    ['Saudi Arabia', 'Spain', 1402],
    ['Saudi Arabia', 'Sri Lanka', 162],
    ['Saudi Arabia', 'Thailand', 62574],
    ['Saudi Arabia', 'Turkey', 6],
    ['Saudi Arabia', 'United Arab Emirates', 96],
    ['Saudi Arabia', 'United Kingdom of Great Britain and Northern Ireland', 14],
    ['Saudi Arabia', 'United States of America', 90510],
    ['Saudi Arabia', 'Viet Nam', 20941]
];